## Imports

In [62]:
import pandas as pd

In [63]:
df_awards_players = pd.read_csv('data/awards_players_processed.csv')
df_coaches = pd.read_csv('data/coaches_processed.csv')
df_players_teams = pd.read_csv('data/players_teams_processed.csv')
df_players = pd.read_csv('data/players.csv')
df_series_post = pd.read_csv('data/series_post_processed.csv')
df_teams = pd.read_csv('data/teams_processed.csv')
df_teams_post = pd.read_csv('data/teams_post_processed.csv')

## Data Cleanup and analysis

Agregate the data from series_post by the number of wins of each player and the number of losses, then join it to the Teams dataset

In [64]:

# Join the team statistics with the second DataFrame
df_teams = pd.merge(df_teams, df_series_post, on=["year", "tmID"], how="left")

df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 47 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          142 non-null    int64
 1   tmID          142 non-null    object
 2   rank          142 non-null    float64
 3   playoff       142 non-null    int64
 4   o_fgm         142 non-null    float64
 5   o_fga         142 non-null    float64
 6   o_ftm         142 non-null    float64
 7   o_fta         142 non-null    float64
 8   o_3pm         142 non-null    float64
 9   o_3pa         142 non-null    float64
 10  o_oreb        142 non-null    float64
 11  o_dreb        142 non-null    float64
 12  o_reb         142 non-null    float64
 13  o_asts        142 non-null    float64
 14  o_pf          142 non-null    float64
 15  o_stl         142 non-null    float64
 16  o_to          142 non-null    float64
 17  o_blk         142 non-null    float64
 18  o_pts         142 non-null    float64
 19  d_fgm         142 non-null    float64
 20  d_fga         142 non-null    float64
 21  d_ftm         142 non-null    float64
 22  d_fta         142 non-null    float64
 23  d_3pm         142 non-null    float64
 24  d_3pa         142 non-null    float64
 25  d_oreb        142 non-null    float64
 26  d_dreb        142 non-null    float64
 27  d_reb         142 non-null    float64
 28  d_asts        142 non-null    float64
 29  d_pf          142 non-null    float64
 30  d_stl         142 non-null    float64
 31  d_to          142 non-null    float64
 32  d_blk         142 non-null    float64
 33  d_pts         142 non-null    float64
 34  GP            142 non-null    float64
 35  homeW         142 non-null    float64
 36  homeL         142 non-null    float64
 37  awayW         142 non-null    float64
 38  awayL         142 non-null    float64
 39  confW         142 non-null    float64
 40  confL         142 non-null    float64
 41  min           142 non-null    float64
 42  attend        142 non-null    float64
 43  total_won     142 non-null    float64
 44  total_lost    142 non-null    float64
 45  total_wins    80 non-null     float64
 46  total_losses  80 non-null     float64
dtypes: float64(44), int64(2), object(1)
memory usage: 52.3+ KB

In [65]:
players_teams_info_df = pd.merge(df_players_teams, df_players, left_on='playerID', right_on='bioID', how='left')
players_teams_info_df.info()
players_teams_info_df = pd.merge(players_teams_info_df, df_awards_players, on=['playerID', 'year'], how='left')
players_teams_info_df.to_csv('players_teams_info.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1876 entries, 0 to 1875
Data columns (total 52 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   playerID            1876 non-null   object
 1   year                1876 non-null   int64
 2   stint               1876 non-null   int64
 3   tmID                1876 non-null   object
 4   GP                  1876 non-null   float64
 5   GS                  1876 non-null   float64
 6   minutes             1876 non-null   float64
 7   points              1876 non-null   float64
 8   oRebounds           1876 non-null   float64
 9   dRebounds           1876 non-null   float64
 10  rebounds            1876 non-null   float64
 11  assists             1876 non-null   float64
 12  steals              1876 non-null   float64
 13  blocks              1876 non-null   float64
 14  turnovers           1876 non-null   float64
 15  PF                  1876 non-null   float64
 16  fgAttempted         1876 non-null   float64
 17  fgMade              1876 non-null   float64
 18  ftAttempted         1876 non-null   float64
 19  ftMade              1876 non-null   float64
 20  threeAttempted      1876 non-null   float64
 21  threeMade           1876 non-null   float64
 22  dq                  1876 non-null   float64
 23  PostGP              1876 non-null   float64
 24  PostGS              1876 non-null   float64
 25  PostMinutes         1876 non-null   float64
 26  PostPoints          1876 non-null   float64
 27  PostoRebounds       1876 non-null   float64
 28  PostdRebounds       1876 non-null   float64
 29  PostRebounds        1876 non-null   float64
 30  PostAssists         1876 non-null   float64
 31  PostSteals          1876 non-null   float64
 32  PostBlocks          1876 non-null   float64
 33  PostTurnovers       1876 non-null   float64
 34  PostPF              1876 non-null   float64
 35  PostfgAttempted     1876 non-null   float64
 36  PostfgMade          1876 non-null   float64
 37  PostftAttempted     1876 non-null   float64
 38  PostftMade          1876 non-null   float64
 39  PostthreeAttempted  1876 non-null   float64
 40  PostthreeMade       1876 non-null   float64
 41  PostDQ              1876 non-null   float64
 42  bioID               1876 non-null   object
 43  pos                 1876 non-null   object
 44  firstseason         1876 non-null   int64
 45  lastseason          1876 non-null   int64
 46  height              1876 non-null   float64
 47  weight              1876 non-null   int64
 48  college             1674 non-null   object
 49  collegeOther        16 non-null     object
 50  birthDate           1876 non-null   object
 51  deathDate           1876 non-null   object
dtypes: float64(39), int64(5), object(8)
memory usage: 762.2+ KB

In [66]:
agg_players_df = players_teams_info_df.groupby(["year", "tmID"]).agg({
    "GP": "sum",
    "GS": "sum",
    "minutes": "mean",
    "points": "sum",
    "oRebounds": "sum",
    "dRebounds": "sum",
    "rebounds": "sum",
    "assists": "sum",
    "steals": "sum",
    "blocks": "sum",
    "turnovers": "sum",
    "PF": "sum",
    "fgAttempted": "sum",
    "fgMade": "sum",
    "ftAttempted": "sum",
    "ftMade": "sum",
    "threeAttempted": "sum",
    "threeMade": "sum",
    "PostGP": "sum",
    "PostGS": "sum",
    "PostMinutes": "sum",
    "PostPoints": "sum",
    "PostoRebounds": "sum",
    "PostdRebounds": "sum",
    "PostRebounds": "sum",
    "PostAssists": "sum",
    "PostSteals": "sum",
    "PostBlocks": "sum",
    "PostTurnovers": "sum",
    "PostPF": "sum",
    "PostfgAttempted": "sum",
    "PostfgMade": "sum",
    "PostftAttempted": "sum",
    "PostftMade": "sum",
    "PostthreeAttempted": "sum",
    "PostthreeMade": "sum",
    "PostDQ": "sum",
    "height": "mean",
    "weight": "mean",
    "award_count": "sum",

    # Add more columns you want to aggregate here
}).reset_index()

df_teams = pd.merge(df_teams, agg_players_df, on=['year', 'tmID'], how='left')
agg_players_df.head()

,year,tmID,GP,GS,minutes,points,oRebounds,dRebounds,rebounds,assists,...,PostfgAttempted,PostfgMade,PostftAttempted,PostftMade,PostthreeAttempted,PostthreeMade,PostDQ,height,weight,award_count
0,1,CHA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.692308,168.846154,0.0
1,1,CLE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.923077,162.846154,1.0
2,1,DET,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.461538,162.923077,0.0
3,1,HOU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.083333,167.916667,4.0
4,1,IND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72.333333,168.000000,0.0

In [67]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 87 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                142 non-null    int64
 1   tmID                142 non-null    object
 2   rank                142 non-null    float64
 3   playoff             142 non-null    int64
 4   o_fgm               142 non-null    float64
 5   o_fga               142 non-null    float64
 6   o_ftm               142 non-null    float64
 7   o_fta               142 non-null    float64
 8   o_3pm               142 non-null    float64
 9   o_3pa               142 non-null    float64
 10  o_oreb              142 non-null    float64
 11  o_dreb              142 non-null    float64
 12  o_reb               142 non-null    float64
 13  o_asts              142 non-null    float64
 14  o_pf                142 non-null    float64
 15  o_stl               142 non-null    float64
 16  o_to                142 non-null    float64
 17  o_blk               142 non-null    float64
 18  o_pts               142 non-null    float64
 19  d_fgm               142 non-null    float64
 20  d_fga               142 non-null    float64
 21  d_ftm               142 non-null    float64
 22  d_fta               142 non-null    float64
 23  d_3pm               142 non-null    float64
 24  d_3pa               142 non-null    float64
 25  d_oreb              142 non-null    float64
 26  d_dreb              142 non-null    float64
 27  d_reb               142 non-null    float64
 28  d_asts              142 non-null    float64
 29  d_pf                142 non-null    float64
 30  d_stl               142 non-null    float64
 31  d_to                142 non-null    float64
 32  d_blk               142 non-null    float64
 33  d_pts               142 non-null    float64
 34  GP_x                142 non-null    float64
 35  homeW               142 non-null    float64
 36  homeL               142 non-null    float64
 37  awayW               142 non-null    float64
 38  awayL               142 non-null    float64
 39  confW               142 non-null    float64
 40  confL               142 non-null    float64
 41  min                 142 non-null    float64
 42  attend              142 non-null    float64
 43  total_won           142 non-null    float64
 44  total_lost          142 non-null    float64
 45  total_wins          80 non-null     float64
 46  total_losses        80 non-null     float64
 47  GP_y                142 non-null    float64
 48  GS                  142 non-null    float64
 49  minutes             142 non-null    float64
 50  points              142 non-null    float64
 51  oRebounds           142 non-null    float64
 52  dRebounds           142 non-null    float64
 53  rebounds            142 non-null    float64
 54  assists             142 non-null    float64
 55  steals              142 non-null    float64
 56  blocks              142 non-null    float64
 57  turnovers           142 non-null    float64
 58  PF                  142 non-null    float64
 59  fgAttempted         142 non-null    float64
 60  fgMade              142 non-null    float64
 61  ftAttempted         142 non-null    float64
 62  ftMade              142 non-null    float64
 63  threeAttempted      142 non-null    float64
 64  threeMade           142 non-null    float64
 65  PostGP              142 non-null    float64
 66  PostGS              142 non-null    float64
 67  PostMinutes         142 non-null    float64
 68  PostPoints          142 non-null    float64
 69  PostoRebounds       142 non-null    float64
 70  PostdRebounds       142 non-null    float64
 71  PostRebounds        142 non-null    float64
 72  PostAssists         142 non-null    float64
 73  PostSteals          142 non-null    float64
 74  PostBlocks          142 non-null    float64
 75  PostTurnovers       142 non-null    float64
 76  PostPF              142 non-null    float64
 77  PostfgAttempted     142 non-null    float64
 78  PostfgMade          142 non-null    float64
 79  PostftAttempted     142 non-null    float64
 80  PostftMade          142 non-null    float64
 81  PostthreeAttempted  142 non-null    float64
 82  PostthreeMade       142 non-null    float64
 83  PostDQ              142 non-null    float64
 84  height              142 non-null    float64
 85  weight              142 non-null    float64
 86  award_count         142 non-null    float64
dtypes: float64(84), int64(2), object(1)
memory usage: 96.6+ KB

In [68]:
df_teams = pd.merge(df_teams, df_coaches, on=['year', 'tmID'], how='left')
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 91 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                142 non-null    int64
 1   tmID                142 non-null    object
 2   rank                142 non-null    float64
 3   playoff             142 non-null    int64
 4   o_fgm               142 non-null    float64
 5   o_fga               142 non-null    float64
 6   o_ftm               142 non-null    float64
 7   o_fta               142 non-null    float64
 8   o_3pm               142 non-null    float64
 9   o_3pa               142 non-null    float64
 10  o_oreb              142 non-null    float64
 11  o_dreb              142 non-null    float64
 12  o_reb               142 non-null    float64
 13  o_asts              142 non-null    float64
 14  o_pf                142 non-null    float64
 15  o_stl               142 non-null    float64
 16  o_to                142 non-null    float64
 17  o_blk               142 non-null    float64
 18  o_pts               142 non-null    float64
 19  d_fgm               142 non-null    float64
 20  d_fga               142 non-null    float64
 21  d_ftm               142 non-null    float64
 22  d_fta               142 non-null    float64
 23  d_3pm               142 non-null    float64
 24  d_3pa               142 non-null    float64
 25  d_oreb              142 non-null    float64
 26  d_dreb              142 non-null    float64
 27  d_reb               142 non-null    float64
 28  d_asts              142 non-null    float64
 29  d_pf                142 non-null    float64
 30  d_stl               142 non-null    float64
 31  d_to                142 non-null    float64
 32  d_blk               142 non-null    float64
 33  d_pts               142 non-null    float64
 34  GP_x                142 non-null    float64
 35  homeW               142 non-null    float64
 36  homeL               142 non-null    float64
 37  awayW               142 non-null    float64
 38  awayL               142 non-null    float64
 39  confW               142 non-null    float64
 40  confL               142 non-null    float64
 41  min                 142 non-null    float64
 42  attend              142 non-null    float64
 43  total_won           142 non-null    float64
 44  total_lost          142 non-null    float64
 45  total_wins          80 non-null     float64
 46  total_losses        80 non-null     float64
 47  GP_y                142 non-null    float64
 48  GS                  142 non-null    float64
 49  minutes             142 non-null    float64
 50  points              142 non-null    float64
 51  oRebounds           142 non-null    float64
 52  dRebounds           142 non-null    float64
 53  rebounds            142 non-null    float64
 54  assists             142 non-null    float64
 55  steals              142 non-null    float64
 56  blocks              142 non-null    float64
 57  turnovers           142 non-null    float64
 58  PF                  142 non-null    float64
 59  fgAttempted         142 non-null    float64
 60  fgMade              142 non-null    float64
 61  ftAttempted         142 non-null    float64
 62  ftMade              142 non-null    float64
 63  threeAttempted      142 non-null    float64
 64  threeMade           142 non-null    float64
 65  PostGP              142 non-null    float64
 66  PostGS              142 non-null    float64
 67  PostMinutes         142 non-null    float64
 68  PostPoints          142 non-null    float64
 69  PostoRebounds       142 non-null    float64
 70  PostdRebounds       142 non-null    float64
 71  PostRebounds        142 non-null    float64
 72  PostAssists         142 non-null    float64
 73  PostSteals          142 non-null    float64
 74  PostBlocks          142 non-null    float64
 75  PostTurnovers       142 non-null    float64
 76  PostPF              142 non-null    float64
 77  PostfgAttempted     142 non-null    float64
 78  PostfgMade          142 non-null    float64
 79  PostftAttempted     142 non-null    float64
 80  PostftMade          142 non-null    float64
 81  PostthreeAttempted  142 non-null    float64
 82  PostthreeMade       142 non-null    float64
 83  PostDQ              142 non-null    float64
 84  height              142 non-null    float64
 85  weight              142 non-null    float64
 86  award_count         142 non-null    float64
 87  won                 142 non-null    float64
 88  lost                142 non-null    float64
 89  post_wins           142 non-null    float64
 90  post_losses         142 non-null    float64
dtypes: float64(88), int64(2), object(1)
memory usage: 101.1+ KB

Merges the teams with teams post and added the value 0 to the teams that did not have any wins or losses

In [69]:
df_teams = pd.merge(df_teams, df_teams_post, on=['year', 'tmID'], how='left').fillna(0)
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 93 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                142 non-null    int64
 1   tmID                142 non-null    object
 2   rank                142 non-null    float64
 3   playoff             142 non-null    int64
 4   o_fgm               142 non-null    float64
 5   o_fga               142 non-null    float64
 6   o_ftm               142 non-null    float64
 7   o_fta               142 non-null    float64
 8   o_3pm               142 non-null    float64
 9   o_3pa               142 non-null    float64
 10  o_oreb              142 non-null    float64
 11  o_dreb              142 non-null    float64
 12  o_reb               142 non-null    float64
 13  o_asts              142 non-null    float64
 14  o_pf                142 non-null    float64
 15  o_stl               142 non-null    float64
 16  o_to                142 non-null    float64
 17  o_blk               142 non-null    float64
 18  o_pts               142 non-null    float64
 19  d_fgm               142 non-null    float64
 20  d_fga               142 non-null    float64
 21  d_ftm               142 non-null    float64
 22  d_fta               142 non-null    float64
 23  d_3pm               142 non-null    float64
 24  d_3pa               142 non-null    float64
 25  d_oreb              142 non-null    float64
 26  d_dreb              142 non-null    float64
 27  d_reb               142 non-null    float64
 28  d_asts              142 non-null    float64
 29  d_pf                142 non-null    float64
 30  d_stl               142 non-null    float64
 31  d_to                142 non-null    float64
 32  d_blk               142 non-null    float64
 33  d_pts               142 non-null    float64
 34  GP_x                142 non-null    float64
 35  homeW               142 non-null    float64
 36  homeL               142 non-null    float64
 37  awayW               142 non-null    float64
 38  awayL               142 non-null    float64
 39  confW               142 non-null    float64
 40  confL               142 non-null    float64
 41  min                 142 non-null    float64
 42  attend              142 non-null    float64
 43  total_won           142 non-null    float64
 44  total_lost          142 non-null    float64
 45  total_wins          142 non-null    float64
 46  total_losses        142 non-null    float64
 47  GP_y                142 non-null    float64
 48  GS                  142 non-null    float64
 49  minutes             142 non-null    float64
 50  points              142 non-null    float64
 51  oRebounds           142 non-null    float64
 52  dRebounds           142 non-null    float64
 53  rebounds            142 non-null    float64
 54  assists             142 non-null    float64
 55  steals              142 non-null    float64
 56  blocks              142 non-null    float64
 57  turnovers           142 non-null    float64
 58  PF                  142 non-null    float64
 59  fgAttempted         142 non-null    float64
 60  fgMade              142 non-null    float64
 61  ftAttempted         142 non-null    float64
 62  ftMade              142 non-null    float64
 63  threeAttempted      142 non-null    float64
 64  threeMade           142 non-null    float64
 65  PostGP              142 non-null    float64
 66  PostGS              142 non-null    float64
 67  PostMinutes         142 non-null    float64
 68  PostPoints          142 non-null    float64
 69  PostoRebounds       142 non-null    float64
 70  PostdRebounds       142 non-null    float64
 71  PostRebounds        142 non-null    float64
 72  PostAssists         142 non-null    float64
 73  PostSteals          142 non-null    float64
 74  PostBlocks          142 non-null    float64
 75  PostTurnovers       142 non-null    float64
 76  PostPF              142 non-null    float64
 77  PostfgAttempted     142 non-null    float64
 78  PostfgMade          142 non-null    float64
 79  PostftAttempted     142 non-null    float64
 80  PostftMade          142 non-null    float64
 81  PostthreeAttempted  142 non-null    float64
 82  PostthreeMade       142 non-null    float64
 83  PostDQ              142 non-null    float64
 84  height              142 non-null    float64
 85  weight              142 non-null    float64
 86  award_count         142 non-null    float64
 87  won                 142 non-null    float64
 88  lost                142 non-null    float64
 89  post_wins           142 non-null    float64
 90  post_losses         142 non-null    float64
 91  W                   142 non-null    float64
 92  L                   142 non-null    float64
dtypes: float64(90), int64(2), object(1)
memory usage: 103.3+ KB

In [70]:
df_teams.to_csv('final_data.csv', index=False)