## Imports

In [2]:
import pandas as pd

In [3]:
df_awards_players = pd.read_csv('data/awards_players.csv')
df_coaches = pd.read_csv('data/coaches.csv')
df_players_teams = pd.read_csv('data/players_teams.csv')
df_players = pd.read_csv('data/players.csv')
df_series_post = pd.read_csv('data/series_post.csv')
df_teams = pd.read_csv('data/teams.csv')
df_teams_post = pd.read_csv('data/teams_post.csv')

## Data Cleanup and analysis

In [4]:
pd.set_option('display.max_columns', None)
df_teams.head()

,year,lgID,tmID,franchID,confID,divID,rank,playoff,seeded,firstRound,semis,finals,name,o_fgm,o_fga,o_ftm,o_fta,o_3pm,o_3pa,o_oreb,o_dreb,o_reb,o_asts,o_pf,o_stl,o_to,o_blk,o_pts,d_fgm,d_fga,d_ftm,d_fta,d_3pm,d_3pa,d_oreb,d_dreb,d_reb,d_asts,d_pf,d_stl,d_to,d_blk,d_pts,tmORB,tmDRB,tmTRB,opptmORB,opptmDRB,opptmTRB,won,lost,GP,homeW,homeL,awayW,awayL,confW,confL,min,attend,arena
0,9,WNBA,ATL,ATL,EA,NaN,7,N,0,NaN,NaN,NaN,Atlanta Dream,895,2258,542,725,202,598,340,737,1077,492,796,285,593,142,2534,1014,2254,679,918,172,502,401,864,1265,684,726,310,561,134,2879,0,0,0,0,0,0,4,30,34,1,16,3,14,2,18,6825,141379,Philips Arena
1,10,WNBA,ATL,ATL,EA,NaN,2,Y,0,L,NaN,NaN,Atlanta Dream,1089,2428,569,755,114,374,404,855,1259,547,741,329,590,121,2861,996,2363,624,807,181,530,353,821,1174,615,700,347,601,133,2797,0,0,0,0,0,0,18,16,34,12,5,6,11,10,12,6950,120737,Philips Arena
2,1,WNBA,CHA,CHA,EA,NaN,8,N,0,NaN,NaN,NaN,Charlotte Sting,812,1903,431,577,131,386,305,630,935,551,713,222,496,90,2186,879,1930,533,716,138,423,326,664,990,596,596,259,426,123,2429,0,0,0,0,0,0,8,24,32,5,11,3,13,5,16,6475,90963,Charlotte Coliseum
3,2,WNBA,CHA,CHA,EA,NaN,4,Y,0,W,W,L,Charlotte Sting,746,1780,410,528,153,428,309,639,948,467,605,217,474,114,2055,732,1846,431,562,114,369,344,567,911,443,579,257,447,124,2009,0,0,0,0,0,0,18,14,32,11,5,7,9,15,6,6500,105525,Charlotte Coliseum
4,3,WNBA,CHA,CHA,EA,NaN,2,Y,0,L,NaN,NaN,Charlotte Sting,770,1790,490,663,211,527,302,653,955,496,647,241,408,105,2241,778,1807,444,598,133,372,295,620,915,489,600,208,424,103,2133,0,0,0,0,0,0,18,14,32,11,5,7,9,12,9,6450,106670,Charlotte Coliseum

In [5]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 61 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        142 non-null    int64
 1   lgID        142 non-null    object
 2   tmID        142 non-null    object
 3   franchID    142 non-null    object
 4   confID      142 non-null    object
 5   divID       0 non-null      float64
 6   rank        142 non-null    int64
 7   playoff     142 non-null    object
 8   seeded      142 non-null    int64
 9   firstRound  80 non-null     object
 10  semis       38 non-null     object
 11  finals      20 non-null     object
 12  name        142 non-null    object
 13  o_fgm       142 non-null    int64
 14  o_fga       142 non-null    int64
 15  o_ftm       142 non-null    int64
 16  o_fta       142 non-null    int64
 17  o_3pm       142 non-null    int64
 18  o_3pa       142 non-null    int64
 19  o_oreb      142 non-null    int64
 20  o_dreb      142 non-null    int64
 21  o_reb       142 non-null    int64
 22  o_asts      142 non-null    int64
 23  o_pf        142 non-null    int64
 24  o_stl       142 non-null    int64
 25  o_to        142 non-null    int64
 26  o_blk       142 non-null    int64
 27  o_pts       142 non-null    int64
 28  d_fgm       142 non-null    int64
 29  d_fga       142 non-null    int64
 30  d_ftm       142 non-null    int64
 31  d_fta       142 non-null    int64
 32  d_3pm       142 non-null    int64
 33  d_3pa       142 non-null    int64
 34  d_oreb      142 non-null    int64
 35  d_dreb      142 non-null    int64
 36  d_reb       142 non-null    int64
 37  d_asts      142 non-null    int64
 38  d_pf        142 non-null    int64
 39  d_stl       142 non-null    int64
 40  d_to        142 non-null    int64
 41  d_blk       142 non-null    int64
 42  d_pts       142 non-null    int64
 43  tmORB       142 non-null    int64
 44  tmDRB       142 non-null    int64
 45  tmTRB       142 non-null    int64
 46  opptmORB    142 non-null    int64
 47  opptmDRB    142 non-null    int64
 48  opptmTRB    142 non-null    int64
 49  won         142 non-null    int64
 50  lost        142 non-null    int64
 51  GP          142 non-null    int64
 52  homeW       142 non-null    int64
 53  homeL       142 non-null    int64
 54  awayW       142 non-null    int64
 55  awayL       142 non-null    int64
 56  confW       142 non-null    int64
 57  confL       142 non-null    int64
 58  min         142 non-null    int64
 59  attend      142 non-null    int64
 60  arena       142 non-null    object
dtypes: float64(1), int64(50), object(10)
memory usage: 67.8+ KB

In [6]:

def drop_columns_with_all_nan(df):
    # Step 1: Check for columns with all NaN values
    columns_to_drop = []
    for col in df.columns:
        unique_values = df[col].unique()
        if len(unique_values) == 1 or all(pd.isna(x) for x in unique_values):
            columns_to_drop.append(col)

    # Step 2: Drop identified columns
    df.drop(columns=columns_to_drop, inplace=True)

    # Step 3: Print the identified columns to be dropped
    print(columns_to_drop)

In [7]:
drop_columns_with_all_nan(df_teams)
print(df_teams.duplicated().sum())
df_teams.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_teams_post)
print(df_teams_post.duplicated().sum())
df_teams_post.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_series_post)
print(df_series_post.duplicated().sum())
df_series_post.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_players)
print(df_players.duplicated().sum())
df_players.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_players_teams)
print(df_players_teams.duplicated().sum())
df_players_teams.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_coaches)
print(df_coaches.duplicated().sum())
print(df_coaches.duplicated(subset=['tmID', 'year']).sum())
df_coaches.drop_duplicates(inplace=True)

drop_columns_with_all_nan(df_awards_players)
print(df_awards_players.duplicated().sum())
df_awards_players.drop_duplicates(inplace=True)

['lgID', 'divID', 'seeded', 'tmORB', 'tmDRB', 'tmTRB', 'opptmORB', 'opptmDRB', 'opptmTRB']
0
['lgID']
0
['lgIDWinner', 'lgIDLoser']
0
['firstseason', 'lastseason']
0
['lgID']
0
['lgID']
0
20
['lgID']
0

In [8]:
df_teams.isnull().sum()

year            0
tmID            0
franchID        0
confID          0
rank            0
playoff         0
firstRound     62
semis         104
finals        122
name            0
o_fgm           0
o_fga           0
o_ftm           0
o_fta           0
o_3pm           0
o_3pa           0
o_oreb          0
o_dreb          0
o_reb           0
o_asts          0
o_pf            0
o_stl           0
o_to            0
o_blk           0
o_pts           0
d_fgm           0
d_fga           0
d_ftm           0
d_fta           0
d_3pm           0
d_3pa           0
d_oreb          0
d_dreb          0
d_reb           0
d_asts          0
d_pf            0
d_stl           0
d_to            0
d_blk           0
d_pts           0
won             0
lost            0
GP              0
homeW           0
homeL           0
awayW           0
awayL           0
confW           0
confL           0
min             0
attend          0
arena           0
dtype: int64

In teams firstRound, Playoffs and finals with The Letter W to signify they won(1) and the letter L(0) to signify they lost, nan means they did not make it to that round. Changing th e NAN for -1, din't play.

In [9]:
# Define the columns to replace NaN values
columns_to_replace = ["firstRound", "semis", "finals"]

# Replace NaN with "DP" in the specified columns
df_teams[columns_to_replace] = df_teams[columns_to_replace].fillna(-1)
replace_dict = {"W": 1, "L": 0}

# Replace "W" with 1 and "L" with 0 in the specified columns
df_teams[columns_to_replace] = df_teams[columns_to_replace].replace(replace_dict)

replace_dict = {"Y": 1, "N": 0}
df_teams['playoff']= df_teams['playoff'].replace(replace_dict)

## Agregating data

Agregate the data from series_post by the number of wins of each player and the number of losses, then join it to the Teams dataset

In [10]:
winning_team_stats = df_series_post.groupby(["year", "tmIDWinner"])[["W"]].sum().reset_index()
winning_team_stats.columns = ["year", "tmID", "total_wins"]

losing_team_stats = df_series_post.groupby(["year", "tmIDLoser"])[["L"]].sum().reset_index()
losing_team_stats.columns = ["year", "tmID", "total_losses"]

# Merge the winning and losing team statistics
team_stats = winning_team_stats.merge(losing_team_stats, on=["year", "tmID"], how="outer").fillna(0)

# Join the team statistics with the second DataFrame
df_teams = pd.merge(df_teams, team_stats, on=["year", "tmID"], how="left")
df_teams[['total_wins', 'total_losses']] = df_teams[['total_wins', 'total_losses']].fillna(0)

df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 54 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          142 non-null    int64
 1   tmID          142 non-null    object
 2   franchID      142 non-null    object
 3   confID        142 non-null    object
 4   rank          142 non-null    int64
 5   playoff       142 non-null    int64
 6   firstRound    142 non-null    int64
 7   semis         142 non-null    int64
 8   finals        142 non-null    int64
 9   name          142 non-null    object
 10  o_fgm         142 non-null    int64
 11  o_fga         142 non-null    int64
 12  o_ftm         142 non-null    int64
 13  o_fta         142 non-null    int64
 14  o_3pm         142 non-null    int64
 15  o_3pa         142 non-null    int64
 16  o_oreb        142 non-null    int64
 17  o_dreb        142 non-null    int64
 18  o_reb         142 non-null    int64
 19  o_asts        142 non-null    int64
 20  o_pf          142 non-null    int64
 21  o_stl         142 non-null    int64
 22  o_to          142 non-null    int64
 23  o_blk         142 non-null    int64
 24  o_pts         142 non-null    int64
 25  d_fgm         142 non-null    int64
 26  d_fga         142 non-null    int64
 27  d_ftm         142 non-null    int64
 28  d_fta         142 non-null    int64
 29  d_3pm         142 non-null    int64
 30  d_3pa         142 non-null    int64
 31  d_oreb        142 non-null    int64
 32  d_dreb        142 non-null    int64
 33  d_reb         142 non-null    int64
 34  d_asts        142 non-null    int64
 35  d_pf          142 non-null    int64
 36  d_stl         142 non-null    int64
 37  d_to          142 non-null    int64
 38  d_blk         142 non-null    int64
 39  d_pts         142 non-null    int64
 40  won           142 non-null    int64
 41  lost          142 non-null    int64
 42  GP            142 non-null    int64
 43  homeW         142 non-null    int64
 44  homeL         142 non-null    int64
 45  awayW         142 non-null    int64
 46  awayL         142 non-null    int64
 47  confW         142 non-null    int64
 48  confL         142 non-null    int64
 49  min           142 non-null    int64
 50  attend        142 non-null    int64
 51  arena         142 non-null    object
 52  total_wins    142 non-null    float64
 53  total_losses  142 non-null    float64
dtypes: float64(2), int64(47), object(5)
memory usage: 60.0+ KB

sums awards by player and year, merges the team players with the awards

In [11]:
award_counts = df_awards_players.groupby(["year", "playerID"]).size().reset_index(name="award_count")
print(award_counts.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         82 non-null     int64
 1   playerID     82 non-null     object
 2   award_count  82 non-null     int64
dtypes: int64(2), object(1)
memory usage: 2.0+ KB
None

In [12]:
players_teams_info_df = pd.merge(df_players_teams, df_players, left_on='playerID', right_on='bioID', how='left')
players_teams_info_df.info()
players_teams_info_df = pd.merge(players_teams_info_df, award_counts, on=['playerID', 'year'], how='left')
players_teams_info_df.to_csv('players_teams_info.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1876 entries, 0 to 1875
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   playerID            1876 non-null   object
 1   year                1876 non-null   int64
 2   stint               1876 non-null   int64
 3   tmID                1876 non-null   object
 4   GP                  1876 non-null   int64
 5   GS                  1876 non-null   int64
 6   minutes             1876 non-null   int64
 7   points              1876 non-null   int64
 8   oRebounds           1876 non-null   int64
 9   dRebounds           1876 non-null   int64
 10  rebounds            1876 non-null   int64
 11  assists             1876 non-null   int64
 12  steals              1876 non-null   int64
 13  blocks              1876 non-null   int64
 14  turnovers           1876 non-null   int64
 15  PF                  1876 non-null   int64
 16  fgAttempted         1876 non-null   int64
 17  fgMade              1876 non-null   int64
 18  ftAttempted         1876 non-null   int64
 19  ftMade              1876 non-null   int64
 20  threeAttempted      1876 non-null   int64
 21  threeMade           1876 non-null   int64
 22  dq                  1876 non-null   int64
 23  PostGP              1876 non-null   int64
 24  PostGS              1876 non-null   int64
 25  PostMinutes         1876 non-null   int64
 26  PostPoints          1876 non-null   int64
 27  PostoRebounds       1876 non-null   int64
 28  PostdRebounds       1876 non-null   int64
 29  PostRebounds        1876 non-null   int64
 30  PostAssists         1876 non-null   int64
 31  PostSteals          1876 non-null   int64
 32  PostBlocks          1876 non-null   int64
 33  PostTurnovers       1876 non-null   int64
 34  PostPF              1876 non-null   int64
 35  PostfgAttempted     1876 non-null   int64
 36  PostfgMade          1876 non-null   int64
 37  PostftAttempted     1876 non-null   int64
 38  PostftMade          1876 non-null   int64
 39  PostthreeAttempted  1876 non-null   int64
 40  PostthreeMade       1876 non-null   int64
 41  PostDQ              1876 non-null   int64
 42  bioID               1876 non-null   object
 43  pos                 1876 non-null   object
 44  height              1876 non-null   float64
 45  weight              1876 non-null   int64
 46  college             1674 non-null   object
 47  collegeOther        16 non-null     object
 48  birthDate           1876 non-null   object
 49  deathDate           1876 non-null   object
dtypes: float64(1), int64(41), object(8)
memory usage: 732.9+ KB

In [13]:
agg_players_df = players_teams_info_df.groupby(["year", "tmID"]).agg({
    "GP": "sum",
    "GS": "sum",
    "minutes": "mean",
    "points": "sum",
    "oRebounds": "sum",
    "dRebounds": "sum",
    "rebounds": "sum",
    "assists": "sum",
    "steals": "sum",
    "blocks": "sum",
    "turnovers": "sum",
    "PF": "sum",
    "fgAttempted": "sum",
    "fgMade": "sum",
    "ftAttempted": "sum",
    "ftMade": "sum",
    "threeAttempted": "sum",
    "threeMade": "sum",
    "PostGP": "sum",
    "PostGS": "sum",
    "PostMinutes": "sum",
    "PostPoints": "sum",
    "PostoRebounds": "sum",
    "PostdRebounds": "sum",
    "PostRebounds": "sum",
    "PostAssists": "sum",
    "PostSteals": "sum",
    "PostBlocks": "sum",
    "PostTurnovers": "sum",
    "PostPF": "sum",
    "PostfgAttempted": "sum",
    "PostfgMade": "sum",
    "PostftAttempted": "sum",
    "PostftMade": "sum",
    "PostthreeAttempted": "sum",
    "PostthreeMade": "sum",
    "PostDQ": "sum",
    "height": "mean",
    "weight": "mean",
    "award_count": "sum",

    # Add more columns you want to aggregate here
}).reset_index()

df_teams = pd.merge(df_teams, agg_players_df, on=['year', 'tmID'], how='left')
agg_players_df.head()

,year,tmID,GP,GS,minutes,points,oRebounds,dRebounds,rebounds,assists,steals,blocks,turnovers,PF,fgAttempted,fgMade,ftAttempted,ftMade,threeAttempted,threeMade,PostGP,PostGS,PostMinutes,PostPoints,PostoRebounds,PostdRebounds,PostRebounds,PostAssists,PostSteals,PostBlocks,PostTurnovers,PostPF,PostfgAttempted,PostfgMade,PostftAttempted,PostftMade,PostthreeAttempted,PostthreeMade,PostDQ,height,weight,award_count
0,1,CHA,318,160,498.076923,2186,305,630,935,551,222,90,483,713,1903,812,577,431,386,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.692308,168.846154,0.0
1,1,CLE,313,160,500.000000,2185,331,603,934,539,259,91,529,647,1828,809,570,426,407,141,61,30,1200,358,72,133,205,97,52,13,81,90,340,136,89,63,91,23,0,70.923077,162.846154,1.0
2,1,DET,327,160,494.230769,2331,341,644,985,503,260,88,519,701,1980,868,699,519,273,76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.461538,162.923077,0.0
3,1,HOU,309,160,539.583333,2475,273,724,997,494,284,104,432,554,1894,891,634,521,491,172,47,30,1225,436,63,122,185,70,54,13,73,83,365,155,105,92,90,34,0,72.083333,167.916667,4.0
4,1,IND,307,160,428.333333,2213,285,647,932,501,271,126,493,642,1838,796,569,428,521,193,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,72.333333,168.000000,0.0

In [14]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 94 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                142 non-null    int64
 1   tmID                142 non-null    object
 2   franchID            142 non-null    object
 3   confID              142 non-null    object
 4   rank                142 non-null    int64
 5   playoff             142 non-null    int64
 6   firstRound          142 non-null    int64
 7   semis               142 non-null    int64
 8   finals              142 non-null    int64
 9   name                142 non-null    object
 10  o_fgm               142 non-null    int64
 11  o_fga               142 non-null    int64
 12  o_ftm               142 non-null    int64
 13  o_fta               142 non-null    int64
 14  o_3pm               142 non-null    int64
 15  o_3pa               142 non-null    int64
 16  o_oreb              142 non-null    int64
 17  o_dreb              142 non-null    int64
 18  o_reb               142 non-null    int64
 19  o_asts              142 non-null    int64
 20  o_pf                142 non-null    int64
 21  o_stl               142 non-null    int64
 22  o_to                142 non-null    int64
 23  o_blk               142 non-null    int64
 24  o_pts               142 non-null    int64
 25  d_fgm               142 non-null    int64
 26  d_fga               142 non-null    int64
 27  d_ftm               142 non-null    int64
 28  d_fta               142 non-null    int64
 29  d_3pm               142 non-null    int64
 30  d_3pa               142 non-null    int64
 31  d_oreb              142 non-null    int64
 32  d_dreb              142 non-null    int64
 33  d_reb               142 non-null    int64
 34  d_asts              142 non-null    int64
 35  d_pf                142 non-null    int64
 36  d_stl               142 non-null    int64
 37  d_to                142 non-null    int64
 38  d_blk               142 non-null    int64
 39  d_pts               142 non-null    int64
 40  won                 142 non-null    int64
 41  lost                142 non-null    int64
 42  GP_x                142 non-null    int64
 43  homeW               142 non-null    int64
 44  homeL               142 non-null    int64
 45  awayW               142 non-null    int64
 46  awayL               142 non-null    int64
 47  confW               142 non-null    int64
 48  confL               142 non-null    int64
 49  min                 142 non-null    int64
 50  attend              142 non-null    int64
 51  arena               142 non-null    object
 52  total_wins          142 non-null    float64
 53  total_losses        142 non-null    float64
 54  GP_y                142 non-null    int64
 55  GS                  142 non-null    int64
 56  minutes             142 non-null    float64
 57  points              142 non-null    int64
 58  oRebounds           142 non-null    int64
 59  dRebounds           142 non-null    int64
 60  rebounds            142 non-null    int64
 61  assists             142 non-null    int64
 62  steals              142 non-null    int64
 63  blocks              142 non-null    int64
 64  turnovers           142 non-null    int64
 65  PF                  142 non-null    int64
 66  fgAttempted         142 non-null    int64
 67  fgMade              142 non-null    int64
 68  ftAttempted         142 non-null    int64
 69  ftMade              142 non-null    int64
 70  threeAttempted      142 non-null    int64
 71  threeMade           142 non-null    int64
 72  PostGP              142 non-null    int64
 73  PostGS              142 non-null    int64
 74  PostMinutes         142 non-null    int64
 75  PostPoints          142 non-null    int64
 76  PostoRebounds       142 non-null    int64
 77  PostdRebounds       142 non-null    int64
 78  PostRebounds        142 non-null    int64
 79  PostAssists         142 non-null    int64
 80  PostSteals          142 non-null    int64
 81  PostBlocks          142 non-null    int64
 82  PostTurnovers       142 non-null    int64
 83  PostPF              142 non-null    int64
 84  PostfgAttempted     142 non-null    int64
 85  PostfgMade          142 non-null    int64
 86  PostftAttempted     142 non-null    int64
 87  PostftMade          142 non-null    int64
 88  PostthreeAttempted  142 non-null    int64
 89  PostthreeMade       142 non-null    int64
 90  PostDQ              142 non-null    int64
 91  height              142 non-null    float64
 92  weight              142 non-null    float64
 93  award_count         142 non-null    float64
dtypes: float64(6), int64(83), object(5)
memory usage: 104.4+ KB

In [15]:
agg_coaches_df = df_coaches.groupby(["year", "tmID"]).agg({
    "won": "sum",
    "lost": "sum",
    "post_wins": "sum",
    "post_losses": "sum",
}).reset_index()

df_teams = pd.merge(df_teams, agg_coaches_df, on=['year', 'tmID'], how='left')
agg_players_df.head()

,year,tmID,GP,GS,minutes,points,oRebounds,dRebounds,rebounds,assists,steals,blocks,turnovers,PF,fgAttempted,fgMade,ftAttempted,ftMade,threeAttempted,threeMade,PostGP,PostGS,PostMinutes,PostPoints,PostoRebounds,PostdRebounds,PostRebounds,PostAssists,PostSteals,PostBlocks,PostTurnovers,PostPF,PostfgAttempted,PostfgMade,PostftAttempted,PostftMade,PostthreeAttempted,PostthreeMade,PostDQ,height,weight,award_count
0,1,CHA,318,160,498.076923,2186,305,630,935,551,222,90,483,713,1903,812,577,431,386,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.692308,168.846154,0.0
1,1,CLE,313,160,500.000000,2185,331,603,934,539,259,91,529,647,1828,809,570,426,407,141,61,30,1200,358,72,133,205,97,52,13,81,90,340,136,89,63,91,23,0,70.923077,162.846154,1.0
2,1,DET,327,160,494.230769,2331,341,644,985,503,260,88,519,701,1980,868,699,519,273,76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.461538,162.923077,0.0
3,1,HOU,309,160,539.583333,2475,273,724,997,494,284,104,432,554,1894,891,634,521,491,172,47,30,1225,436,63,122,185,70,54,13,73,83,365,155,105,92,90,34,0,72.083333,167.916667,4.0
4,1,IND,307,160,428.333333,2213,285,647,932,501,271,126,493,642,1838,796,569,428,521,193,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,72.333333,168.000000,0.0

Merges the teams with teams post and added the value 0 to the teams that did not have any wins or losses

In [16]:
df_teams = pd.merge(df_teams, df_teams_post, on=['year', 'tmID'], how='left')
df_teams[['W', 'L']] = df_teams[['W', 'L']].fillna(0)

df_teams.head()

,year,tmID,franchID,confID,rank,playoff,firstRound,semis,finals,name,o_fgm,o_fga,o_ftm,o_fta,o_3pm,o_3pa,o_oreb,o_dreb,o_reb,o_asts,o_pf,o_stl,o_to,o_blk,o_pts,d_fgm,d_fga,d_ftm,d_fta,d_3pm,d_3pa,d_oreb,d_dreb,d_reb,d_asts,d_pf,d_stl,d_to,d_blk,d_pts,won_x,lost_x,GP_x,homeW,homeL,awayW,awayL,confW,confL,min,attend,arena,total_wins,total_losses,GP_y,GS,minutes,points,oRebounds,dRebounds,rebounds,assists,steals,blocks,turnovers,PF,fgAttempted,fgMade,ftAttempted,ftMade,threeAttempted,threeMade,PostGP,PostGS,PostMinutes,PostPoints,PostoRebounds,PostdRebounds,PostRebounds,PostAssists,PostSteals,PostBlocks,PostTurnovers,PostPF,PostfgAttempted,PostfgMade,PostftAttempted,PostftMade,PostthreeAttempted,PostthreeMade,PostDQ,height,weight,award_count,won_y,lost_y,post_wins,post_losses,W,L
0,9,ATL,ATL,EA,7,0,-1,-1,-1,Atlanta Dream,895,2258,542,725,202,598,340,737,1077,492,796,285,593,142,2534,1014,2254,679,918,172,502,401,864,1265,684,726,310,561,134,2879,4,30,34,1,16,3,14,2,18,6825,141379,Philips Arena,0.0,0.0,319,166,454.571429,2314,297,650,947,482,282,115,499,705,2114,818,637,476,598,202,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,73.214286,168.714286,0.0,4,30,0,0,0.0,0.0
1,10,ATL,ATL,EA,2,1,0,-1,-1,Atlanta Dream,1089,2428,569,755,114,374,404,855,1259,547,741,329,590,121,2861,996,2363,624,807,181,530,353,821,1174,615,700,347,601,133,2797,18,16,34,12,5,6,11,10,12,6950,120737,Philips Arena,0.0,0.0,351,170,534.692308,2861,404,855,1259,547,329,121,567,741,2428,1089,755,569,374,114,19,10,402,168,21,40,61,33,15,4,41,45,135,58,60,40,29,12,0,72.538462,159.076923,1.0,18,16,0,2,0.0,2.0
2,1,CHA,CHA,EA,8,0,-1,-1,-1,Charlotte Sting,812,1903,431,577,131,386,305,630,935,551,713,222,496,90,2186,879,1930,533,716,138,423,326,664,990,596,596,259,426,123,2429,8,24,32,5,11,3,13,5,16,6475,90963,Charlotte Coliseum,0.0,0.0,318,160,498.076923,2186,305,630,935,551,222,90,483,713,1903,812,577,431,386,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.692308,168.846154,0.0,8,24,0,0,0.0,0.0
3,2,CHA,CHA,EA,4,1,1,1,0,Charlotte Sting,746,1780,410,528,153,428,309,639,948,467,605,217,474,114,2055,732,1846,431,562,114,369,344,567,911,443,579,257,447,124,2009,18,14,32,11,5,7,9,15,6,6500,105525,Charlotte Coliseum,4.0,0.0,302,160,541.666667,2055,309,639,948,467,217,114,464,605,1780,746,528,410,428,153,72,40,1600,463,67,146,213,112,49,31,104,143,429,177,90,70,103,39,0,71.500000,164.416667,0.0,18,14,4,4,4.0,4.0
4,3,CHA,CHA,EA,2,1,0,-1,-1,Charlotte Sting,770,1790,490,663,211,527,302,653,955,496,647,241,408,105,2241,778,1807,444,598,133,372,295,620,915,489,600,208,424,103,2133,18,14,32,11,5,7,9,12,9,6450,106670,Charlotte Coliseum,0.0,0.0,269,160,466.000000,2146,270,594,864,478,228,90,366,586,1708,737,627,465,516,207,17,10,369,104,18,38,56,27,14,4,23,28,114,42,19,9,42,11,0,71.307692,164.923077,0.0,18,14,0,2,0.0,2.0

In [17]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 100 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                142 non-null    int64
 1   tmID                142 non-null    object
 2   franchID            142 non-null    object
 3   confID              142 non-null    object
 4   rank                142 non-null    int64
 5   playoff             142 non-null    int64
 6   firstRound          142 non-null    int64
 7   semis               142 non-null    int64
 8   finals              142 non-null    int64
 9   name                142 non-null    object
 10  o_fgm               142 non-null    int64
 11  o_fga               142 non-null    int64
 12  o_ftm               142 non-null    int64
 13  o_fta               142 non-null    int64
 14  o_3pm               142 non-null    int64
 15  o_3pa               142 non-null    int64
 16  o_oreb              142 non-null    int64
 17  o_dreb              142 non-null    int64
 18  o_reb               142 non-null    int64
 19  o_asts              142 non-null    int64
 20  o_pf                142 non-null    int64
 21  o_stl               142 non-null    int64
 22  o_to                142 non-null    int64
 23  o_blk               142 non-null    int64
 24  o_pts               142 non-null    int64
 25  d_fgm               142 non-null    int64
 26  d_fga               142 non-null    int64
 27  d_ftm               142 non-null    int64
 28  d_fta               142 non-null    int64
 29  d_3pm               142 non-null    int64
 30  d_3pa               142 non-null    int64
 31  d_oreb              142 non-null    int64
 32  d_dreb              142 non-null    int64
 33  d_reb               142 non-null    int64
 34  d_asts              142 non-null    int64
 35  d_pf                142 non-null    int64
 36  d_stl               142 non-null    int64
 37  d_to                142 non-null    int64
 38  d_blk               142 non-null    int64
 39  d_pts               142 non-null    int64
 40  won_x               142 non-null    int64
 41  lost_x              142 non-null    int64
 42  GP_x                142 non-null    int64
 43  homeW               142 non-null    int64
 44  homeL               142 non-null    int64
 45  awayW               142 non-null    int64
 46  awayL               142 non-null    int64
 47  confW               142 non-null    int64
 48  confL               142 non-null    int64
 49  min                 142 non-null    int64
 50  attend              142 non-null    int64
 51  arena               142 non-null    object
 52  total_wins          142 non-null    float64
 53  total_losses        142 non-null    float64
 54  GP_y                142 non-null    int64
 55  GS                  142 non-null    int64
 56  minutes             142 non-null    float64
 57  points              142 non-null    int64
 58  oRebounds           142 non-null    int64
 59  dRebounds           142 non-null    int64
 60  rebounds            142 non-null    int64
 61  assists             142 non-null    int64
 62  steals              142 non-null    int64
 63  blocks              142 non-null    int64
 64  turnovers           142 non-null    int64
 65  PF                  142 non-null    int64
 66  fgAttempted         142 non-null    int64
 67  fgMade              142 non-null    int64
 68  ftAttempted         142 non-null    int64
 69  ftMade              142 non-null    int64
 70  threeAttempted      142 non-null    int64
 71  threeMade           142 non-null    int64
 72  PostGP              142 non-null    int64
 73  PostGS              142 non-null    int64
 74  PostMinutes         142 non-null    int64
 75  PostPoints          142 non-null    int64
 76  PostoRebounds       142 non-null    int64
 77  PostdRebounds       142 non-null    int64
 78  PostRebounds        142 non-null    int64
 79  PostAssists         142 non-null    int64
 80  PostSteals          142 non-null    int64
 81  PostBlocks          142 non-null    int64
 82  PostTurnovers       142 non-null    int64
 83  PostPF              142 non-null    int64
 84  PostfgAttempted     142 non-null    int64
 85  PostfgMade          142 non-null    int64
 86  PostftAttempted     142 non-null    int64
 87  PostftMade          142 non-null    int64
 88  PostthreeAttempted  142 non-null    int64
 89  PostthreeMade       142 non-null    int64
 90  PostDQ              142 non-null    int64
 91  height              142 non-null    float64
 92  weight              142 non-null    float64
 93  award_count         142 non-null    float64
 94  won_y               142 non-null    int64
 95  lost_y              142 non-null    int64
 96  post_wins           142 non-null    int64
 97  post_losses         142 non-null    int64
 98  W                   142 non-null    float64
 99  L                   142 non-null    float64
dtypes: float64(8), int64(87), object(5)
memory usage: 111.1+ KB

## Transform categorical data

In [18]:
df_teams.drop(columns=['tmID', 'franchID', 'name', 'arena'], inplace=True)

In [19]:
from sklearn.preprocessing import OneHotEncoder

categorical_features = df_teams.select_dtypes(include=['object'])
categorical_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   confID  142 non-null    object
dtypes: object(1)
memory usage: 1.2+ KB

In [20]:
encoder = OneHotEncoder()
for feature in categorical_features:
    onehotarray = encoder.fit_transform(df_teams[[feature]]).toarray()
    items = [f'{feature}_{item}' for item in encoder.categories_[0]]
    df_teams[items] = onehotarray
data=df_teams.drop(categorical_features, axis=1)
data.head()

,year,rank,playoff,firstRound,semis,finals,o_fgm,o_fga,o_ftm,o_fta,o_3pm,o_3pa,o_oreb,o_dreb,o_reb,o_asts,o_pf,o_stl,o_to,o_blk,o_pts,d_fgm,d_fga,d_ftm,d_fta,d_3pm,d_3pa,d_oreb,d_dreb,d_reb,d_asts,d_pf,d_stl,d_to,d_blk,d_pts,won_x,lost_x,GP_x,homeW,homeL,awayW,awayL,confW,confL,min,attend,total_wins,total_losses,GP_y,GS,minutes,points,oRebounds,dRebounds,rebounds,assists,steals,blocks,turnovers,PF,fgAttempted,fgMade,ftAttempted,ftMade,threeAttempted,threeMade,PostGP,PostGS,PostMinutes,PostPoints,PostoRebounds,PostdRebounds,PostRebounds,PostAssists,PostSteals,PostBlocks,PostTurnovers,PostPF,PostfgAttempted,PostfgMade,PostftAttempted,PostftMade,PostthreeAttempted,PostthreeMade,PostDQ,height,weight,award_count,won_y,lost_y,post_wins,post_losses,W,L,confID_EA,confID_WE
0,9,7,0,-1,-1,-1,895,2258,542,725,202,598,340,737,1077,492,796,285,593,142,2534,1014,2254,679,918,172,502,401,864,1265,684,726,310,561,134,2879,4,30,34,1,16,3,14,2,18,6825,141379,0.0,0.0,319,166,454.571429,2314,297,650,947,482,282,115,499,705,2114,818,637,476,598,202,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,73.214286,168.714286,0.0,4,30,0,0,0.0,0.0,1.0,0.0
1,10,2,1,0,-1,-1,1089,2428,569,755,114,374,404,855,1259,547,741,329,590,121,2861,996,2363,624,807,181,530,353,821,1174,615,700,347,601,133,2797,18,16,34,12,5,6,11,10,12,6950,120737,0.0,0.0,351,170,534.692308,2861,404,855,1259,547,329,121,567,741,2428,1089,755,569,374,114,19,10,402,168,21,40,61,33,15,4,41,45,135,58,60,40,29,12,0,72.538462,159.076923,1.0,18,16,0,2,0.0,2.0,1.0,0.0
2,1,8,0,-1,-1,-1,812,1903,431,577,131,386,305,630,935,551,713,222,496,90,2186,879,1930,533,716,138,423,326,664,990,596,596,259,426,123,2429,8,24,32,5,11,3,13,5,16,6475,90963,0.0,0.0,318,160,498.076923,2186,305,630,935,551,222,90,483,713,1903,812,577,431,386,131,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,71.692308,168.846154,0.0,8,24,0,0,0.0,0.0,1.0,0.0
3,2,4,1,1,1,0,746,1780,410,528,153,428,309,639,948,467,605,217,474,114,2055,732,1846,431,562,114,369,344,567,911,443,579,257,447,124,2009,18,14,32,11,5,7,9,15,6,6500,105525,4.0,0.0,302,160,541.666667,2055,309,639,948,467,217,114,464,605,1780,746,528,410,428,153,72,40,1600,463,67,146,213,112,49,31,104,143,429,177,90,70,103,39,0,71.500000,164.416667,0.0,18,14,4,4,4.0,4.0,1.0,0.0
4,3,2,1,0,-1,-1,770,1790,490,663,211,527,302,653,955,496,647,241,408,105,2241,778,1807,444,598,133,372,295,620,915,489,600,208,424,103,2133,18,14,32,11,5,7,9,12,9,6450,106670,0.0,0.0,269,160,466.000000,2146,270,594,864,478,228,90,366,586,1708,737,627,465,516,207,17,10,369,104,18,38,56,27,14,4,23,28,114,42,19,9,42,11,0,71.307692,164.923077,0.0,18,14,0,2,0.0,2.0,1.0,0.0

In [21]:
data.to_csv('final_data.csv', index=False)